// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEDWV9pa260W71v2u1OoP_Vc6EcVvFhBg',
    appId: '1:751238632242:web:f58d4e7fced9f3b2cc3d2b',
    messagingSenderId: '751238632242',
    projectId: 'jorenaresidence-f9074',
    authDomain: 'jorenaresidence-f9074.firebaseapp.com',
    storageBucket: 'jorenaresidence-f9074.firebasestorage.app',
    measurementId: 'G-YMSK8V9ZTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5BLgxPO8P03jnj595aWATlJcHMHVOx5g',
    appId: '1:751238632242:android:5d5e8f83d4f439d1cc3d2b',
    messagingSenderId: '751238632242',
    projectId: 'jorenaresidence-f9074',
    storageBucket: 'jorenaresidence-f9074.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV0X4F2y2JLySko_1gFLGk6nEmv3ctxxw',
    appId: '1:751238632242:ios:a80c4721d8e73207cc3d2b',
    messagingSenderId: '751238632242',
    projectId: 'jorenaresidence-f9074',
    storageBucket: 'jorenaresidence-f9074.firebasestorage.app',
    iosBundleId: 'com.example.aplikasismartresidence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEDWV9pa260W71v2u1OoP_Vc6EcVvFhBg',
    appId: '1:751238632242:web:c5c98c27835c638fcc3d2b',
    messagingSenderId: '751238632242',
    projectId: 'jorenaresidence-f9074',
    authDomain: 'jorenaresidence-f9074.firebaseapp.com',
    storageBucket: 'jorenaresidence-f9074.firebasestorage.app',
    measurementId: 'G-W680RZYY5P',
  );
}
